### PR TITLE
Bugfix/home not defined

### PR DESCRIPTION
**Pull request by monwolf**
Windows 11 doesn't define by default home env in when you are using Powershell, I modified the funtion GetHomePath to get the home from the SO package if the env var isn't set.

### CODE REVIEW

**Comment by synfinatic** [comment]
Same comment as the previous PR.  This change included the fix for the passthrough bug.  Also, before I merge I guess I gotta spin up my Windows VM :)

**Comment by monwolf** [comment]
Makes sense your comment, feel free to ask me anything if you need some clarification. I tried don't change the original behaviour of your code adding windows support.  

PS: Thanks for merging this will be really useful for us, it will allow running lens without the headaches of temporal keys .

**Comment by synfinatic** [comment]
So I tried this change under both PowerShell and Git/Bash for Windows and both error out because there's another bug because all the file handling in my code assumes `/` as the delim and Windows of course uses `\`.   Should be relatively straight forward to fix, but this PR doesn't work for me as-is and so I'm not going to merge.

Anyways, need to do my "real job" so gonna have to deal with this later this evening.  Opened #100

**Comment by monwolf** [comment]
Hmm...  Can you share how are your config? I'm using  this one:

```
SSOConfig:
    company-sso:
        SSORegion: us-east-1
        StartUrl: https://company-sso.awsapps.com/start
        Accounts:  # optional block for specifying tags & overrides
            accountid:
                Name: my-account-name
                DefaultRegion: eu-west-1
                Tags:  # tags for all roles in the account
                    env: prod
                    project: myproject
                Roles:
                    AdministratorAccess:
                        DefaultRegion: eu-west-1
                        Tags:  # tags specific for this role (will override account level tags)
                            env: prod
                            project: myproject
                            role: adm

DefaultSSO: xxx-sso
LogLevel: warn
LogLines: true
UrlAction: print
SecureStore: json
JsonStore: ~/aws-sso/store.json
```


And it's working fine for me:

 CMD:
image

PS 5.1
image

PS 7.1.4
image

And git bash
image

**Comment by synfinatic** [comment]
```
 ./aws-sso-1.2.1-beta-windows-amd64.exe list
level=error msg="Unable to open CacheStore: C:\\Users\\aturner/.aws-sso/cache.json" error="open C:\\Users\\aturner/.aws-sso/cache.json: The system cannot find the file specified."
```

```
SSOConfig:
    Default:
        SSORegion: us-east-1
        StartUrl: https://<magic value>.awsapps.com/start

SecureStore: wincred
LogLevel: warn
DefaultRegion: us-east-1
```

That said, the above error is not fatal.  the file not actually there.  but after completing the run it actually creates it in the correct location and then can access it because apparently Windows doesn't care about `/` vs `\` anymore?

**Comment by monwolf** [comment]
maybe it's the Windows version I'm currently testing in Version 21H1 or maybe could be the go version? I'm compiling it with version 1.17.2

**Comment by synfinatic** [comment]
well, the `cache.json` did not exist at all when the error was generated.  once it was auto-created, it no longer generated the error.  For now at least, it's best to "do the right thing" and use [path/filepath](https://pkg.go.dev/path/filepath) to do the right thing.

**Comment by monwolf** [comment]
Now I normalized the output of the path using this std library:
image

**Comment by synfinatic** [comment]
Closing this since I wanted to clean this up a bit more and add unit tests.  See #103

**Pull request closed without merging**
