### PR TITLE
whitespace in profile names must be replaced by -

### LINKED ISSUE #552: Generated profile names contain whitespaces
**Output of `aws-sso version`:**
```
AWS SSO CLI Version 1.11.0 -- Copyright 2021-2022 Aaron Turner
ea15d31f496ce9e7c13bb76c562a738748bfac47 (v1.11.0) built at 2023-08-03T02:44:01+0000
```

**Describe the bug:**
If you set `ProfileFormat: '{{ .AccountAlias }}:{{ .RoleName }}'` in your `~/.aws-sso/config.yaml` and the AccountName of the AWS Account is eg. set to "My Account" the profile may be generated like
```
[profile My Account:ReadOnly]
credential_process = /opt/homebrew/bin/aws-sso -u open -S "foo" process --arn arn:aws:iam::12
345678912:role/ReadOnly
region = eu-central-1
```
According [the docs](https://docs.aws.amazon.com/sdkref/latest/guide/file-format.html) named profiles don't allow spaces 

**To Reproduce:**
 1. Create AWS Account and set the AccountName to "My Account" (mind the space)
 2. set `ProfileFormat: '{{ .AccountAlias }}:{{ .RoleName }}'` in your `~/.aws-sso/config.yaml`
 3. Let `aws-sso` generate your `~/.aws/config` file
 4. You won't be able to use the resulting named profile eg. with the `aws-cli` [profile My Account:MyRole]` because of the whitespace

**Expected behavior:**
Saces are replaced by something valid, eg. "-"

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 13.5

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
    foo:
        SSORegion: eu-central-1
        StartUrl: https://bar.awsapps.com/start
        DefaultRegion: eu-central-1
DefaultRegion: eu-central-1
ConsoleDuration: 60
CacheRefresh: 8
AutoConfigCheck: true
UrlAction: open
ConfigProfilesUrlAction: open
LogLevel: error
HistoryLimit: 10
HistoryMinutes: 1440
ProfileFormat: '{{ .AccountAlias }}:{{ .RoleName }}'
```

### PR DESCRIPTION
**Pull request by PacoVK**
closes #552 

If there are whitespaces in the AccountName, replace them all by "-"

### CODE REVIEW

**Comment by synfinatic** [comment]
So the FAQ covers this situation today: https://github.com/synfinatic/aws-sso-cli/blob/main/docs/FAQ.md#how-to-configure-profileformat

Basically, I get that this is a problem for users.  I also know some people will want to replace spaces with `-` or `_` or just remove them completely.   I've been thinking about what the best way to solve this is, and I think I'd rather change the default `ProfileFormat` to do the substitution.  Then if people want something different, they can change that setting.

Reasonable?

**Comment by synfinatic** [comment]
Oh right... the current default is:

```
const DEFAULT_PROFILE_TEMPLATE = "{{.AccountIdPad}}:{{.RoleName}}"
```

So no spaces are in the default.   Also, now I've had my coffee, I notice you say `AccountName` not `AccountAlias`.   `AccountName` is controlled by you in the `config.yaml` file.  So maybe don't use spaces?  Or strip them for the `ProfileName` as described in the FAQ?

**Comment by PacoVK** [comment]
Argh, yes I was tricked again! Ofc I am talking about accountAlias here 😂 well that fix needs to be ported to AccountAlias to make sense

**Comment by synfinatic** [comment]
So even for `AccountAlias` I would not approve this PR because this is easily fixed per the FAQ.

**Comment by PacoVK** [comment]
Missed that part, totally makes sense!

**Pull request closed without merging**
